export const MOCK_CATEGORIES = [
  { name: "Crypto", active: true },
  { name: "Geopolitics", active: false },
  { name: "Stocks", active: false },
  { name: "AI & Tech", active: false },
  { name: "Sports", active: false },
  { name: "Global News", active: false },
  { name: "Entertainment", active: false },
];

export const MOCK_TRENDING = [
  {
    id: "eth-5k",
    title: "Will Ethereum reach $5,000 by the end of Q3...",
    category: "Crypto",
    chance: "12%",
    volume: "$842k",
    iconName: "activity",
  },
  {
    id: "us-election",
    title: "2024 US Presidential Election: Democrat...",
    category: "Geopolitics",
    chance: "48%",
    volume: "$12.1M",
    iconName: "landmark",
  },
  {
    id: "gpt-5",
    title: "OpenAI to release GPT-5 before December 2024?",
    category: "AI",
    chance: "74%",
    volume: "$1.2M",
    iconName: "rocket",
  },
];

export const MOCK_NEWEST = [
  {
    id: "fomc-cut",
    title: "Fed to cut interest rates in the next FOMC meeting?",
    tags: ["Stocks", "Added 2h ago"],
    metricLabel: "Current Chance",
    metricValue: "32%",
    metricColor: "text-primary",
    iconName: "check",
  },
  {
    id: "nba-champ",
    title: "Who will win the 2024 NBA Championship?",
    tags: ["Sports", "Added 5h ago"],
    metricLabel: "Pool Size",
    metricValue: "$240k",
    metricColor: "text-primary",
    iconName: "trophy",
  },
];

export const MOCK_CLOSING = [
  {
    id: "btc-70k",
    tag: "URGENT",
    time: "2h 14m left",
    title: "Bitcoin to close above $70k today?",
    progress: 85,
    tagColor: "text-red-400",
  },
  {
    id: "superbowl",
    tag: "ENDING TODAY",
    time: "8h 45m left",
    title: "Super Bowl viewership record broken?",
    progress: 25,
    tagColor: "text-orange-400",
  },
  {
    id: "apple-vr",
    tag: "LAST CHANCE",
    time: "12h 02m left",
    title: "Apple's VR headset shipment numbers?",
    progress: 60,
    tagColor: "text-red-300",
  },
];

export const MOCK_MARKET_STATS = {
  traders24h: "12,402",
  totalTvl: "$45.8M",
  activeMarkets: "1,894",
};

export const MOCK_FEATURED_MARKET = {
  id: "spacex-moon",
  tag: "FEATURED MARKET",
  volume: "~$2.4M Volume",
  titlePrefix: "Will SpaceX achieve a ",
  titleHighlight: "Moon Landing",
  titleSuffix: " before Jan 2026?",
  probability: "68%",
  endsIn: "14d : 22h",
  yesPrice: "68¢",
  noPrice: "32¢",
  currentOdds: "1.47x",
};

// biome-ignore lint/suspicious/noExplicitAny: MOCK_DB allows arbitrary values for simplicity
export const MOCK_DB: Record<string, any> = {
  "spacex-moon": {
    category: "Space",
    subcategory: "EXPLORATION",
    titlePrefix: "Will SpaceX achieve a ",
    titleHighlight: "Moon Landing",
    titleSuffix: " before Jan 2026?",
    probability: "68%",
    volume: "$2.48M",
    liquidity: "$842.1K",
    expiration: "Jan 1, 2026",
    yesPrice: "68.4¢",
    noPrice: "31.6¢",
  },
  "eth-5k": {
    category: "Crypto",
    subcategory: "PRICES",
    titlePrefix: "Will Ethereum reach ",
    titleHighlight: "$5,000",
    titleSuffix: " by the end of Q3?",
    probability: "12%",
    volume: "$842K",
    liquidity: "$210K",
    expiration: "Sep 30",
    yesPrice: "12.0¢",
    noPrice: "88.0¢",
  },
  "gpt-5": {
    category: "Tech & AI",
    subcategory: "LLM BENCHMARKS",
    titlePrefix: "Will ",
    titleHighlight: "GPT-5",
    titleSuffix: " be released before December 31, 2024?",
    probability: "74%",
    volume: "$1.2M",
    liquidity: "$450K",
    expiration: "Dec 31, 2024",
    yesPrice: "74.0¢",
    noPrice: "26.0¢",
  },
  "us-election": {
    category: "Geopolitics",
    subcategory: "US POLITICS",
    titlePrefix: "2024 US Presidential Election: ",
    titleHighlight: "Democrat Win?",
    titleSuffix: "",
    probability: "48%",
    volume: "$12.1M",
    liquidity: "$4.1M",
    expiration: "Nov 5, 2024",
    yesPrice: "48.0¢",
    noPrice: "52.0¢",
  },
};

export const MOCK_PORTFOLIO_DATA = {
  stats: {
    totalValue: "$124,502.80",
    unrealizedPnl: "+$14,205.50",
    unrealizedPnlPercent: "+12.8%",
    availableBalance: "$42,800.00",
  },
  activePositions: [
    {
      id: "btc-100k",
      market: "Will Bitcoin hit $100k in 2024?",
      outcome: "YES",
      positionSize: "15,000 shares",
      avgPrice: "$0.45",
      currentPrice: "$0.62",
      unrealizedPnl: "+$2,550.00",
      pnlPositive: true,
    },
    {
      id: "us-election",
      market: "US Presidential Election Winner",
      outcome: "NO (Candidate A)",
      positionSize: "8,500 shares",
      avgPrice: "$0.82",
      currentPrice: "$0.78",
      unrealizedPnl: "-$340.00",
      pnlPositive: false,
    },
    {
      id: "fed-cut",
      market: "Fed Interest Rate Cut in June",
      outcome: "YES",
      positionSize: "22,000 shares",
      avgPrice: "$0.25",
      currentPrice: "$0.55",
      unrealizedPnl: "+$6,600.00",
      pnlPositive: true,
    },
    {
      id: "eth-etf",
      market: "Ethereum Spot ETF Approval",
      outcome: "YES",
      positionSize: "10,000 shares",
      avgPrice: "$0.35",
      currentPrice: "$0.88",
      unrealizedPnl: "+$5,300.00",
      pnlPositive: true,
    },
  ],
  recentActivity: [
    {
      id: "act-1",
      action: "Bought 5,000 shares of 'YES'",
      subtext: "Will Bitcoin hit $100k in 2024?",
      amount: "-$2,250.00",
      date: "Today, 14:32",
      isDeposit: false,
      amountPositive: false,
      icon: "plus",
    },
    {
      id: "act-2",
      action: "Sold 2,000 shares of 'NO'",
      subtext: "US Presidential Election Winner",
      amount: "+$1,560.00",
      date: "Yesterday, 09:15",
      isDeposit: false,
      amountPositive: true,
      icon: "arrow-right-left",
    },
    {
      id: "act-3",
      action: "Deposit via USDC",
      subtext: "Wallet ending in 8x4A",
      amount: "+$10,000.00",
      date: "Oct 24, 11:20",
      isDeposit: true,
      amountPositive: true,
      icon: "wallet",
    },
  ],
};
